#!/bin/bash -x

project=$1
hostnames=${2}
host='docker.janmyr.com'
image="andersjanmyr/$project"
dns="${project}.janmyr.com"
if [ -n "$hostnames" ]; then
  dns="$dns,$hostnames"
fi

env_file_option=''
pushd ~/Projects/secrets
if [ -f "$project/env" ]; then
  scp -r $project $host:/tmp
  env_file_option="--env-file /tmp/$project/env"
fi
popd

ssh $host "\
  docker pull $image; \
  docker kill $project; \
  docker rm $project; \
  docker run -d \
  --restart unless-stopped \
  -e VIRTUAL_HOST=$dns \
  $env_file_option \
  --name $project \
  $image"


